const { makeErrorMappingProxy } = require('@aragon/contract-helpers-test')

module.exports = makeErrorMappingProxy({
  // aragonOS errors
  APP_AUTH_FAILED: 'APP_AUTH_FAILED',
  INIT_ALREADY_INITIALIZED: 'INIT_ALREADY_INITIALIZED',
  INIT_NOT_INITIALIZED: 'INIT_NOT_INITIALIZED',
  RECOVER_DISALLOWED: 'RECOVER_DISALLOWED',
  EVMCALLS_CALL_REVERTED: 'EVMCALLS_CALL_REVERTED',
  EVMCALLS_INVALID_LENGTH: 'EVMCALLS_INVALID_LENGTH',
  EVMREG_EXECUTOR_ENABLED: 'EVMREG_EXECUTOR_ENABLED',
